name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Greetings Test
      id: greetings-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Greetings Test
        setup-command: ''
        command: gradle tes
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GREETINGS-TEST_RESULTS: "${{steps.greetings-test.outputs.result}}"
      with:
        runners: greetings-test
